### ISSUE TITLE
how to set new default country 

### ISSUE THREAD

**Issue by LeManhTuong286** [hantrongbinh/vue-country-code#13]
when I set " :defaultCountry="defaultCountry", it worked firsttime, and then it keep this value until I reload page, I tried "this.defaultCountry=null" and set this.defaultCountry= new value, but it not working, 
tks u

**Comment by hantrongbinh** [comment]
`defaultCountry` only works at the first load. Can you provide details of your scenario?

**Comment by hantrongbinh** [comment]
I just updated dynamic `defaultCountry` at v1.1.3
