### ISSUE TITLE
fetch country code api throw error.

### ISSUE THREAD

**Issue by iMnoorfahad** [hantrongbinh/vue-country-code#14]
i used in my web application this, it's working fine but here is some issue if you resolve this.
it's very helpful. when we **fetched current country using api, it throw error** please make in log or something else.

<img width="431" alt="Screenshot 2022-01-10 at 1 20 47 PM" src="https://user-images.githubusercontent.com/28540424/148735016-add28518-01cd-4ebb-a2b2-85556d3c419d.png">

**Comment by hantrongbinh** [comment]
Updated at 1.1.3
