### ISSUE TITLE
Large css file size

### ISSUE THREAD

**Issue by stalker3343** [hantrongbinh/vue-country-code#3]
![изображение](https://user-images.githubusercontent.com/42894422/97070247-a67c8200-15df-11eb-9155-a677ba729e52.png)
![изображение](https://user-images.githubusercontent.com/42894422/97070311-03783800-15e0-11eb-9ee9-b2414f6ca517.png)

**Comment by hantrongbinh** [comment]
I have updated new `sprice.css`
