### ISSUE TITLE
Compilation warning message: Critical dependency

### ISSUE THREAD

**Issue by tecnoloco** [hantrongbinh/vue-country-code#8]
During compilation, I get this output:

```
 WARNING  Compiled with 1 warnings                                                                                                                                                        
 warning  in ./node_modules/vue-country-code/dist/vue-country-code.js

Critical dependency: the request of a dependency is an expression

```
This after updating to 1.0.7

**Comment by hantrongbinh** [comment]
I just published the new version, please update package to `1.0.8` to fix critical dependency

**Comment by tecnoloco** [comment]
Updated to 1.0.8 but I still get the same WARNING 😢

**Comment by hantrongbinh** [comment]
hmmm. I think I used `parcel` to bundle this package so it is the bug of `parcel`

https://github.com/parcel-bundler/parcel/issues/2883

**Comment by tecnoloco** [comment]
What about using vue-cli 3 for bundling?

**Comment by hantrongbinh** [comment]
Okay. I will try it in my free time.

**Comment by chris-hud** [comment]
Just wanted to give our +1 for this issue.

**Comment by uwejan** [comment]
+1 here;
```
 WARNING  Compiled with 1 warnings                                                                                                                                                                                                                           12:24:42 PM

 warning  in ./node_modules/vue-country-code/dist/vue-country-code.js

Critical dependency: the request of a dependency is an expression

```

**Comment by hjelmdal** [comment]
This is getting critical. Can't you just rollback to the version that actually functioned well?

**Comment by hantrongbinh** [comment]
I recently publish `v1.1.0`. This issue is fixed completely.  Try it guys

**Comment by uwejan** [comment]
@hantrongbinh i just did the upgrade, now i get his error;
```Module not found: Error: Can't resolve 'vue-country-code/dist/vue-country-code.css'```
advice please?

**Comment by tecnoloco** [comment]
@uwejan css is now injected by js, you just need to delete the css import. Despite I don´t like this solution (using rollup as builder and have it all in one js), it solves the warning. I will try to make implementation with vue-cli 3 if @hantrongbinh is ok with that.

**Comment by hantrongbinh** [comment]
@tecnoloco it's cool. I'll be happy with your contribution

**Comment by hjelmdal** [comment]
@tecnoloco, any news? :D

**Comment by hjelmdal** [comment]
Can anyone solve this? Otherwise I have to be looking around for other options, as this has been breaking my build for way to long now. I hope that @hantrongbinh or @tecnoloco at least can give an update asap, before I start looking for alternatives (which I would rather avoid :-) )

**Comment by hantrongbinh** [comment]
@hjelmdal Have you try `v1.1.0` yet? And what is your problem?

**Comment by hjelmdal** [comment]
@hantrongbinh have a look here: 
`
ERROR in ./node_modules/vue-country-code/dist/vue-country-code.css (./node_modules/css-loader??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./node_modules/vue-country-code/dist/vue-country-code.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: ENOENT: no such file or directory, open '/Users/stephanhjelmdalnielsen/.web/WePlan V3/http/node_modules/vue-country-code/dist/vue-country-code.css'
 @ ./node_modules/vue-country-code/dist/vue-country-code.css 2:14-129
`

**Comment by hantrongbinh** [comment]
@hjelmdal you no longer have to import css in the new version. I'm going to update `README` soon
